// District names are compiled from public Ghana Local Government Service
// records at time of writing. MMDA boundaries are occasionally split or
// renamed by legislative instrument — re-verify against the Ghana
// Statistical Service / Local Government Ministry before relying on this
// list for anything compliance-sensitive.

export interface GhanaRegion {
  name: string;
  capital: string;
  districts: string[];
}

export const GHANA_REGIONS: GhanaRegion[] = [
  {
    name: 'Ahafo',
    capital: 'Goaso',
    districts: [
      'Asunafo North Municipal',
      'Asunafo South',
      'Asutifi North',
      'Asutifi South',
      'Tano North Municipal',
      'Tano South Municipal',
    ],
  },
  {
    name: 'Ashanti',
    capital: 'Kumasi',
    districts: [
      'Adansi Asokwa',
      'Adansi North',
      'Adansi South',
      'Afigya Kwabre North',
      'Afigya Kwabre South',
      'Ahafo Ano North Municipal',
      'Ahafo Ano South East',
      'Ahafo Ano South West',
      'Akrofuom',
      'Amansie Central',
      'Amansie South',
      'Amansie West',
      'Asante Akim Central Municipal',
      'Asante Akim North Municipal',
      'Asante Akim South Municipal',
      'Asokore Mampong Municipal',
      'Asokwa Municipal',
      'Atwima Kwanwoma',
      'Atwima Mponua',
      'Atwima Nwabiagya Municipal',
      'Atwima Nwabiagya North',
      'Bekwai Municipal',
      'Bosome Freho',
      'Bosomtwe',
      'Ejisu Municipal',
      'Ejura Sekyedumase Municipal',
      'Juaben Municipal',
      'Kumasi Metropolitan',
      'Kwabre East Municipal',
      'Kwadaso Municipal',
      'Mampong Municipal',
      'Obuasi East',
      'Obuasi Municipal',
      'Offinso Municipal',
      'Offinso North',
      'Oforikrom Municipal',
      'Old Tafo Municipal',
      'Sekyere Afram Plains',
      'Sekyere Central',
      'Sekyere East',
      'Sekyere Kumawu',
      'Sekyere South',
      'Suame Municipal',
    ],
  },
  {
    name: 'Bono',
    capital: 'Sunyani',
    districts: [
      'Banda',
      'Berekum East Municipal',
      'Berekum West',
      'Dormaa Central Municipal',
      'Dormaa East',
      'Dormaa West',
      'Jaman North',
      'Jaman South Municipal',
      'Sunyani Municipal',
      'Sunyani West',
      'Tain',
      'Wenchi Municipal',
    ],
  },
  {
    name: 'Bono East',
    capital: 'Techiman',
    districts: [
      'Atebubu Amantin Municipal',
      'Kintampo North Municipal',
      'Kintampo South',
      'Nkoranza North',
      'Nkoranza South Municipal',
      'Pru East',
      'Pru West',
      'Sene East',
      'Sene West',
      'Techiman Municipal',
      'Techiman North',
    ],
  },
  {
    name: 'Central',
    capital: 'Cape Coast',
    districts: [
      'Abura Asebu Kwamankese',
      'Agona East',
      'Agona West Municipal',
      'Ajumako Enyan Essiam',
      'Asikuma Odoben Brakwa',
      'Assin Central Municipal',
      'Assin North Municipal',
      'Assin South',
      'Awutu Senya East Municipal',
      'Awutu Senya West',
      'Cape Coast Metropolitan',
      'Effutu Municipal',
      'Ekumfi',
      'Gomoa Central',
      'Gomoa East',
      'Gomoa West',
      'Mfantseman Municipal',
      'Twifo Atti-Morkwa',
      'Twifo Hemang Lower Denkyira',
      'Upper Denkyira East Municipal',
      'Upper Denkyira West',
    ],
  },
  {
    name: 'Eastern',
    capital: 'Koforidua',
    districts: [
      'Abuakwa North Municipal',
      'Abuakwa South Municipal',
      'Achiase',
      'Akuapem North Municipal',
      'Akuapem South',
      'Akyemansa',
      'Asene Manso Akroso',
      'Asuogyaman',
      'Atiwa East',
      'Atiwa West',
      'Ayensuano',
      'Birim Central Municipal',
      'Birim North',
      'Birim South',
      'Denkyembour',
      'East Akim Municipal',
      'Fanteakwa North',
      'Fanteakwa South',
      'Kwaebibirem Municipal',
      'Kwahu Afram Plains North',
      'Kwahu Afram Plains South',
      'Kwahu East',
      'Kwahu South',
      'Kwahu West Municipal',
      'Lower Manya Krobo Municipal',
      'New Juaben North Municipal',
      'New Juaben South Municipal',
      'Nsawam Adoagyiri Municipal',
      'Okere',
      'Suhum Municipal',
      'Upper Manya Krobo',
      'Upper West Akim',
      'West Akim Municipal',
      'Yilo Krobo Municipal',
    ],
  },
  {
    name: 'Greater Accra',
    capital: 'Accra',
    districts: [
      'Ablekuma Central Municipal',
      'Ablekuma North Municipal',
      'Ablekuma West Municipal',
      'Accra Metropolitan',
      'Ada East',
      'Ada West',
      'Adenta Municipal',
      'Ashaiman Municipal',
      'Ayawaso Central Municipal',
      'Ayawaso East Municipal',
      'Ayawaso North Municipal',
      'Ayawaso West Municipal',
      'Ga Central Municipal',
      'Ga East Municipal',
      'Ga North Municipal',
      'Ga South Municipal',
      'Ga West Municipal',
      'Kpone Katamanso Municipal',
      'Krowor Municipal',
      'La Dade-Kotopon Municipal',
      'La Nkwantanang Madina Municipal',
      'Ledzokuku Municipal',
      'Ningo Prampram',
      'Okaikwei North Municipal',
      'Shai Osudoku',
      'Tema Metropolitan',
      'Tema West Municipal',
      'Weija Gbawe Municipal',
    ],
  },
  {
    name: 'North East',
    capital: 'Nalerigu',
    districts: [
      'Bunkpurugu Nyakpanduri',
      'Chereponi',
      'East Mamprusi Municipal',
      'Mamprugu Moagduri',
      'West Mamprusi Municipal',
      'Yunyoo-Nasuan',
    ],
  },
  {
    name: 'Northern',
    capital: 'Tamale',
    districts: [
      'Gushegu Municipal',
      'Karaga',
      'Kpandai',
      'Kumbungu',
      'Mion',
      'Nanton',
      'Nanumba North Municipal',
      'Nanumba South',
      'Saboba',
      'Sagnarigu Municipal',
      'Savelugu Municipal',
      'Tamale Metropolitan',
      'Tatale Sanguli',
      'Tolon',
      'Yendi Municipal',
      'Zabzugu',
    ],
  },
  {
    name: 'Oti',
    capital: 'Dambai',
    districts: [
      'Biakoye',
      'Guan',
      'Jasikan',
      'Kadjebi',
      'Krachi East Municipal',
      'Krachi Nchumuru',
      'Krachi West',
      'Nkwanta North',
      'Nkwanta South Municipal',
    ],
  },
  {
    name: 'Savannah',
    capital: 'Damongo',
    districts: [
      'Bole',
      'Central Gonja',
      'East Gonja Municipal',
      'North East Gonja',
      'North Gonja',
      'Sawla-Tuna-Kalba',
      'West Gonja Municipal',
    ],
  },
  {
    name: 'Upper East',
    capital: 'Bolgatanga',
    districts: [
      'Bawku Municipal',
      'Bawku West',
      'Binduri',
      'Bolgatanga East',
      'Bolgatanga Municipal',
      'Bongo',
      'Builsa North Municipal',
      'Builsa South',
      'Garu',
      'Kassena Nankana Municipal',
      'Kassena Nankana West',
      'Nabdam',
      'Pusiga',
      'Talensi',
      'Tempane',
    ],
  },
  {
    name: 'Upper West',
    capital: 'Wa',
    districts: [
      'Daffiama Bussie Issa',
      'Jirapa Municipal',
      'Lambussie Karni',
      'Lawra Municipal',
      'Nadowli-Kaleo',
      'Nandom Municipal',
      'Sissala East Municipal',
      'Sissala West',
      'Wa East',
      'Wa Municipal',
      'Wa West',
    ],
  },
  {
    name: 'Volta',
    capital: 'Ho',
    districts: [
      'Adaklu',
      'Afadzato South',
      'Agotime Ziope',
      'Akatsi North',
      'Akatsi South',
      'Anloga',
      'Central Tongu',
      'Ho Municipal',
      'Ho West',
      'Hohoe Municipal',
      'Keta Municipal',
      'Ketu North Municipal',
      'Ketu South Municipal',
      'Kpando Municipal',
      'North Dayi',
      'North Tongu',
      'South Dayi',
      'South Tongu',
    ],
  },
  {
    name: 'Western',
    capital: 'Sekondi-Takoradi',
    districts: [
      'Ahanta West Municipal',
      'Effia Kwesimintsim Municipal',
      'Ellembelle',
      'Jomoro Municipal',
      'Mpohor',
      'Nzema East Municipal',
      'Prestea Huni-Valley Municipal',
      'Sekondi-Takoradi Metropolitan',
      'Shama',
      'Tarkwa-Nsuaem Municipal',
      'Wassa Amenfi Central',
      'Wassa Amenfi East Municipal',
      'Wassa Amenfi West',
      'Wassa East',
    ],
  },
  {
    name: 'Western North',
    capital: 'Sefwi Wiawso',
    districts: [
      'Aowin Municipal',
      'Bia East',
      'Bia West',
      'Bibiani Anhwiaso Bekwai Municipal',
      'Bodi',
      'Juaboso',
      'Sefwi Akontombra',
      'Sefwi Wiawso Municipal',
      'Suaman',
    ],
  },
];

export const GHANA_REGION_NAMES = GHANA_REGIONS.map((region) => region.name);

export function getDistrictsForRegion(regionName: string): string[] {
  return GHANA_REGIONS.find((region) => region.name === regionName)?.districts ?? [];
}
