-- ============================================================================
-- 2026-09-25. Owner-approved ("Option 1"). Paste AFTER 20260925a and 20260925b.
--
-- WHO MAY CLAIM WHICH SKILL OR SPECIALTY, ENFORCED IN THE DATABASE.
--
-- The app already shows each role only the skills and specialties it may
-- claim (constants/skillEligibility.ts). Until now that rule existed only in
-- the app, so a write straight to the database, bypassing the app, could
-- still store "Physical examination" or "Cardiology" on a first aider, and
-- the matcher would score them on it.
--
-- THE TABLE IS GENERATED, NEVER HAND-EDITED. The block between the BEGIN and
-- END GENERATED markers is written by lib/claimEligibilitySql.ts from the
-- app's table, and lib/__tests__/claimEligibilitySql.test.ts fails the build
-- if this file or supabase/schema.sql ever differs from it. A later change to
-- the app's table needs a new migration carrying the regenerated block.
--
-- `category` IS TEXT, NOT THE ENUM, ON PURPOSE. schema.sql adds the
-- 'allied_health' enum value and would fill this table in the same
-- transaction, and Postgres refuses to use an enum value in the transaction
-- that added it. Text sidesteps that; the trigger compares new.category::text.
--
-- ONLY NEWLY ADDED ITEMS ARE CHECKED. A skill already on the profile is never
-- refused, for two reasons:
--   * a role change: /api/volunteer-category changes the role first, then the
--     app saves the list without the skills the new role cannot claim. Were
--     held skills re-checked, that first step would fail.
--   * profiles written before this rule: nobody is locked out of saving an
--     unrelated edit because of a skill they already had. No backfill.
--
-- The table has RLS on and no policies or grants: nobody reads it through the
-- API. The trigger function is SECURITY DEFINER so it can read it.
--
-- Idempotent. No begin/commit. Self-checks at the end.
-- ============================================================================

create table if not exists volunteer_claim_eligibility (
  kind text not null check (kind in ('skill', 'specialty')),
  item text not null,
  category text not null,
  constraint volunteer_claim_eligibility_pkey primary key (kind, item, category)
);

alter table volunteer_claim_eligibility enable row level security;
revoke all on volunteer_claim_eligibility from anon, authenticated;

-- BEGIN GENERATED: volunteer_claim_eligibility (lib/claimEligibilitySql.ts, do not edit by hand)
delete from volunteer_claim_eligibility;
insert into volunteer_claim_eligibility (kind, item, category) values
  ('skill', 'Active listening and support', 'allied_health'),
  ('skill', 'Active listening and support', 'doctor'),
  ('skill', 'Active listening and support', 'first_aider'),
  ('skill', 'Active listening and support', 'midwife'),
  ('skill', 'Active listening and support', 'nurse'),
  ('skill', 'Active listening and support', 'other'),
  ('skill', 'Active listening and support', 'pharmacist'),
  ('skill', 'Active listening and support', 'student'),
  ('skill', 'Airway management', 'doctor'),
  ('skill', 'Airway management', 'first_aider'),
  ('skill', 'Airway management', 'midwife'),
  ('skill', 'Airway management', 'nurse'),
  ('skill', 'Airway management', 'student'),
  ('skill', 'Antenatal care', 'doctor'),
  ('skill', 'Antenatal care', 'midwife'),
  ('skill', 'Antenatal care', 'nurse'),
  ('skill', 'Anthropometric measurement', 'allied_health'),
  ('skill', 'Anthropometric measurement', 'doctor'),
  ('skill', 'Anthropometric measurement', 'first_aider'),
  ('skill', 'Anthropometric measurement', 'midwife'),
  ('skill', 'Anthropometric measurement', 'nurse'),
  ('skill', 'Anthropometric measurement', 'other'),
  ('skill', 'Anthropometric measurement', 'pharmacist'),
  ('skill', 'Anthropometric measurement', 'student'),
  ('skill', 'Automated external defibrillator (AED) use', 'allied_health'),
  ('skill', 'Automated external defibrillator (AED) use', 'doctor'),
  ('skill', 'Automated external defibrillator (AED) use', 'first_aider'),
  ('skill', 'Automated external defibrillator (AED) use', 'midwife'),
  ('skill', 'Automated external defibrillator (AED) use', 'nurse'),
  ('skill', 'Automated external defibrillator (AED) use', 'other'),
  ('skill', 'Automated external defibrillator (AED) use', 'pharmacist'),
  ('skill', 'Automated external defibrillator (AED) use', 'student'),
  ('skill', 'Basic Life Support (BLS)', 'allied_health'),
  ('skill', 'Basic Life Support (BLS)', 'doctor'),
  ('skill', 'Basic Life Support (BLS)', 'first_aider'),
  ('skill', 'Basic Life Support (BLS)', 'midwife'),
  ('skill', 'Basic Life Support (BLS)', 'nurse'),
  ('skill', 'Basic Life Support (BLS)', 'other'),
  ('skill', 'Basic Life Support (BLS)', 'pharmacist'),
  ('skill', 'Basic Life Support (BLS)', 'student'),
  ('skill', 'Birth registration support', 'allied_health'),
  ('skill', 'Birth registration support', 'doctor'),
  ('skill', 'Birth registration support', 'first_aider'),
  ('skill', 'Birth registration support', 'midwife'),
  ('skill', 'Birth registration support', 'nurse'),
  ('skill', 'Birth registration support', 'other'),
  ('skill', 'Birth registration support', 'pharmacist'),
  ('skill', 'Birth registration support', 'student'),
  ('skill', 'Blood glucose testing', 'allied_health'),
  ('skill', 'Blood glucose testing', 'doctor'),
  ('skill', 'Blood glucose testing', 'first_aider'),
  ('skill', 'Blood glucose testing', 'midwife'),
  ('skill', 'Blood glucose testing', 'nurse'),
  ('skill', 'Blood glucose testing', 'pharmacist'),
  ('skill', 'Blood glucose testing', 'student'),
  ('skill', 'Blood pressure measurement', 'allied_health'),
  ('skill', 'Blood pressure measurement', 'doctor'),
  ('skill', 'Blood pressure measurement', 'first_aider'),
  ('skill', 'Blood pressure measurement', 'midwife'),
  ('skill', 'Blood pressure measurement', 'nurse'),
  ('skill', 'Blood pressure measurement', 'pharmacist'),
  ('skill', 'Blood pressure measurement', 'student'),
  ('skill', 'Breast self-examination teaching', 'allied_health'),
  ('skill', 'Breast self-examination teaching', 'doctor'),
  ('skill', 'Breast self-examination teaching', 'first_aider'),
  ('skill', 'Breast self-examination teaching', 'midwife'),
  ('skill', 'Breast self-examination teaching', 'nurse'),
  ('skill', 'Breast self-examination teaching', 'other'),
  ('skill', 'Breast self-examination teaching', 'pharmacist'),
  ('skill', 'Breast self-examination teaching', 'student'),
  ('skill', 'Breastfeeding support', 'doctor'),
  ('skill', 'Breastfeeding support', 'midwife'),
  ('skill', 'Breastfeeding support', 'nurse'),
  ('skill', 'Breastfeeding support', 'student'),
  ('skill', 'Burns management', 'allied_health'),
  ('skill', 'Burns management', 'doctor'),
  ('skill', 'Burns management', 'first_aider'),
  ('skill', 'Burns management', 'midwife'),
  ('skill', 'Burns management', 'nurse'),
  ('skill', 'Burns management', 'pharmacist'),
  ('skill', 'Burns management', 'student'),
  ('skill', 'Cardiopulmonary resuscitation (CPR)', 'allied_health'),
  ('skill', 'Cardiopulmonary resuscitation (CPR)', 'doctor'),
  ('skill', 'Cardiopulmonary resuscitation (CPR)', 'first_aider'),
  ('skill', 'Cardiopulmonary resuscitation (CPR)', 'midwife'),
  ('skill', 'Cardiopulmonary resuscitation (CPR)', 'nurse'),
  ('skill', 'Cardiopulmonary resuscitation (CPR)', 'other'),
  ('skill', 'Cardiopulmonary resuscitation (CPR)', 'pharmacist'),
  ('skill', 'Cardiopulmonary resuscitation (CPR)', 'student'),
  ('skill', 'Cataract screening', 'allied_health'),
  ('skill', 'Cataract screening', 'doctor'),
  ('skill', 'Cataract screening', 'nurse'),
  ('skill', 'Cataract screening', 'student'),
  ('skill', 'Cervical screening (visual inspection with acetic acid)', 'doctor'),
  ('skill', 'Cervical screening (visual inspection with acetic acid)', 'midwife'),
  ('skill', 'Cervical screening (visual inspection with acetic acid)', 'nurse'),
  ('skill', 'Child growth monitoring', 'allied_health'),
  ('skill', 'Child growth monitoring', 'doctor'),
  ('skill', 'Child growth monitoring', 'first_aider'),
  ('skill', 'Child growth monitoring', 'midwife'),
  ('skill', 'Child growth monitoring', 'nurse'),
  ('skill', 'Child growth monitoring', 'pharmacist'),
  ('skill', 'Child growth monitoring', 'student'),
  ('skill', 'Cholesterol and lipid testing', 'allied_health'),
  ('skill', 'Cholesterol and lipid testing', 'doctor'),
  ('skill', 'Cholesterol and lipid testing', 'midwife'),
  ('skill', 'Cholesterol and lipid testing', 'nurse'),
  ('skill', 'Cholesterol and lipid testing', 'pharmacist'),
  ('skill', 'Cholesterol and lipid testing', 'student'),
  ('skill', 'Clinical breast examination', 'doctor'),
  ('skill', 'Clinical breast examination', 'midwife'),
  ('skill', 'Clinical breast examination', 'nurse'),
  ('skill', 'Clinical breast examination', 'student'),
  ('skill', 'Community mobilisation', 'allied_health'),
  ('skill', 'Community mobilisation', 'doctor'),
  ('skill', 'Community mobilisation', 'first_aider'),
  ('skill', 'Community mobilisation', 'midwife'),
  ('skill', 'Community mobilisation', 'nurse'),
  ('skill', 'Community mobilisation', 'other'),
  ('skill', 'Community mobilisation', 'pharmacist'),
  ('skill', 'Community mobilisation', 'student'),
  ('skill', 'Crowd and queue management', 'allied_health'),
  ('skill', 'Crowd and queue management', 'doctor'),
  ('skill', 'Crowd and queue management', 'first_aider'),
  ('skill', 'Crowd and queue management', 'midwife'),
  ('skill', 'Crowd and queue management', 'nurse'),
  ('skill', 'Crowd and queue management', 'other'),
  ('skill', 'Crowd and queue management', 'pharmacist'),
  ('skill', 'Crowd and queue management', 'student'),
  ('skill', 'Data entry', 'allied_health'),
  ('skill', 'Data entry', 'doctor'),
  ('skill', 'Data entry', 'first_aider'),
  ('skill', 'Data entry', 'midwife'),
  ('skill', 'Data entry', 'nurse'),
  ('skill', 'Data entry', 'other'),
  ('skill', 'Data entry', 'pharmacist'),
  ('skill', 'Data entry', 'student'),
  ('skill', 'Dental and oral health screening', 'allied_health'),
  ('skill', 'Dental and oral health screening', 'doctor'),
  ('skill', 'Dental and oral health screening', 'nurse'),
  ('skill', 'Dental and oral health screening', 'student'),
  ('skill', 'Deworming administration', 'doctor'),
  ('skill', 'Deworming administration', 'midwife'),
  ('skill', 'Deworming administration', 'nurse'),
  ('skill', 'Deworming administration', 'pharmacist'),
  ('skill', 'Deworming administration', 'student'),
  ('skill', 'Dispensing spectacles', 'allied_health'),
  ('skill', 'Dispensing spectacles', 'doctor'),
  ('skill', 'Dispensing spectacles', 'midwife'),
  ('skill', 'Dispensing spectacles', 'nurse'),
  ('skill', 'Dispensing spectacles', 'pharmacist'),
  ('skill', 'Dispensing spectacles', 'student'),
  ('skill', 'Donor counselling', 'doctor'),
  ('skill', 'Donor counselling', 'midwife'),
  ('skill', 'Donor counselling', 'nurse'),
  ('skill', 'Donor counselling', 'pharmacist'),
  ('skill', 'Donor counselling', 'student'),
  ('skill', 'Donor eligibility screening', 'doctor'),
  ('skill', 'Donor eligibility screening', 'midwife'),
  ('skill', 'Donor eligibility screening', 'nurse'),
  ('skill', 'Donor eligibility screening', 'pharmacist'),
  ('skill', 'Donor eligibility screening', 'student'),
  ('skill', 'Donor registration', 'allied_health'),
  ('skill', 'Donor registration', 'doctor'),
  ('skill', 'Donor registration', 'first_aider'),
  ('skill', 'Donor registration', 'midwife'),
  ('skill', 'Donor registration', 'nurse'),
  ('skill', 'Donor registration', 'other'),
  ('skill', 'Donor registration', 'pharmacist'),
  ('skill', 'Donor registration', 'student'),
  ('skill', 'Dosage calculation', 'doctor'),
  ('skill', 'Dosage calculation', 'midwife'),
  ('skill', 'Dosage calculation', 'nurse'),
  ('skill', 'Dosage calculation', 'pharmacist'),
  ('skill', 'Dosage calculation', 'student'),
  ('skill', 'Drug interaction screening', 'doctor'),
  ('skill', 'Drug interaction screening', 'pharmacist'),
  ('skill', 'Emergency triage', 'doctor'),
  ('skill', 'Emergency triage', 'first_aider'),
  ('skill', 'Emergency triage', 'midwife'),
  ('skill', 'Emergency triage', 'nurse'),
  ('skill', 'Emergency triage', 'student'),
  ('skill', 'Eye health education', 'allied_health'),
  ('skill', 'Eye health education', 'doctor'),
  ('skill', 'Eye health education', 'first_aider'),
  ('skill', 'Eye health education', 'midwife'),
  ('skill', 'Eye health education', 'nurse'),
  ('skill', 'Eye health education', 'other'),
  ('skill', 'Eye health education', 'pharmacist'),
  ('skill', 'Eye health education', 'student'),
  ('skill', 'Family planning counselling', 'doctor'),
  ('skill', 'Family planning counselling', 'midwife'),
  ('skill', 'Family planning counselling', 'nurse'),
  ('skill', 'Family planning counselling', 'pharmacist'),
  ('skill', 'Family planning counselling', 'student'),
  ('skill', 'Haemoglobin testing', 'allied_health'),
  ('skill', 'Haemoglobin testing', 'doctor'),
  ('skill', 'Haemoglobin testing', 'midwife'),
  ('skill', 'Haemoglobin testing', 'nurse'),
  ('skill', 'Haemoglobin testing', 'pharmacist'),
  ('skill', 'Haemoglobin testing', 'student'),
  ('skill', 'Health education', 'allied_health'),
  ('skill', 'Health education', 'doctor'),
  ('skill', 'Health education', 'first_aider'),
  ('skill', 'Health education', 'midwife'),
  ('skill', 'Health education', 'nurse'),
  ('skill', 'Health education', 'other'),
  ('skill', 'Health education', 'pharmacist'),
  ('skill', 'Health education', 'student'),
  ('skill', 'Hepatitis B screening', 'allied_health'),
  ('skill', 'Hepatitis B screening', 'doctor'),
  ('skill', 'Hepatitis B screening', 'midwife'),
  ('skill', 'Hepatitis B screening', 'nurse'),
  ('skill', 'Hepatitis B screening', 'pharmacist'),
  ('skill', 'Hepatitis B screening', 'student'),
  ('skill', 'HIV counselling and testing', 'allied_health'),
  ('skill', 'HIV counselling and testing', 'doctor'),
  ('skill', 'HIV counselling and testing', 'midwife'),
  ('skill', 'HIV counselling and testing', 'nurse'),
  ('skill', 'HIV counselling and testing', 'pharmacist'),
  ('skill', 'HIV counselling and testing', 'student'),
  ('skill', 'HPV sample collection', 'doctor'),
  ('skill', 'HPV sample collection', 'midwife'),
  ('skill', 'HPV sample collection', 'nurse'),
  ('skill', 'Immunisation counselling', 'doctor'),
  ('skill', 'Immunisation counselling', 'midwife'),
  ('skill', 'Immunisation counselling', 'nurse'),
  ('skill', 'Immunisation counselling', 'pharmacist'),
  ('skill', 'Immunisation counselling', 'student'),
  ('skill', 'Infection control', 'allied_health'),
  ('skill', 'Infection control', 'doctor'),
  ('skill', 'Infection control', 'first_aider'),
  ('skill', 'Infection control', 'midwife'),
  ('skill', 'Infection control', 'nurse'),
  ('skill', 'Infection control', 'pharmacist'),
  ('skill', 'Infection control', 'student'),
  ('skill', 'Injection administration', 'doctor'),
  ('skill', 'Injection administration', 'midwife'),
  ('skill', 'Injection administration', 'nurse'),
  ('skill', 'Injection administration', 'pharmacist'),
  ('skill', 'Injection administration', 'student'),
  ('skill', 'Insecticide-treated net distribution', 'allied_health'),
  ('skill', 'Insecticide-treated net distribution', 'doctor'),
  ('skill', 'Insecticide-treated net distribution', 'first_aider'),
  ('skill', 'Insecticide-treated net distribution', 'midwife'),
  ('skill', 'Insecticide-treated net distribution', 'nurse'),
  ('skill', 'Insecticide-treated net distribution', 'other'),
  ('skill', 'Insecticide-treated net distribution', 'pharmacist'),
  ('skill', 'Insecticide-treated net distribution', 'student'),
  ('skill', 'Intraocular pressure measurement', 'allied_health'),
  ('skill', 'Intraocular pressure measurement', 'doctor'),
  ('skill', 'Intraocular pressure measurement', 'nurse'),
  ('skill', 'Intraocular pressure measurement', 'student'),
  ('skill', 'Inventory management', 'allied_health'),
  ('skill', 'Inventory management', 'doctor'),
  ('skill', 'Inventory management', 'first_aider'),
  ('skill', 'Inventory management', 'midwife'),
  ('skill', 'Inventory management', 'nurse'),
  ('skill', 'Inventory management', 'other'),
  ('skill', 'Inventory management', 'pharmacist'),
  ('skill', 'Inventory management', 'student'),
  ('skill', 'Logistics and setup', 'allied_health'),
  ('skill', 'Logistics and setup', 'doctor'),
  ('skill', 'Logistics and setup', 'first_aider'),
  ('skill', 'Logistics and setup', 'midwife'),
  ('skill', 'Logistics and setup', 'nurse'),
  ('skill', 'Logistics and setup', 'other'),
  ('skill', 'Logistics and setup', 'pharmacist'),
  ('skill', 'Logistics and setup', 'student'),
  ('skill', 'Malaria rapid diagnostic testing', 'allied_health'),
  ('skill', 'Malaria rapid diagnostic testing', 'doctor'),
  ('skill', 'Malaria rapid diagnostic testing', 'midwife'),
  ('skill', 'Malaria rapid diagnostic testing', 'nurse'),
  ('skill', 'Malaria rapid diagnostic testing', 'pharmacist'),
  ('skill', 'Malaria rapid diagnostic testing', 'student'),
  ('skill', 'Malnutrition screening (MUAC)', 'allied_health'),
  ('skill', 'Malnutrition screening (MUAC)', 'doctor'),
  ('skill', 'Malnutrition screening (MUAC)', 'first_aider'),
  ('skill', 'Malnutrition screening (MUAC)', 'midwife'),
  ('skill', 'Malnutrition screening (MUAC)', 'nurse'),
  ('skill', 'Malnutrition screening (MUAC)', 'pharmacist'),
  ('skill', 'Malnutrition screening (MUAC)', 'student'),
  ('skill', 'Medication administration', 'doctor'),
  ('skill', 'Medication administration', 'midwife'),
  ('skill', 'Medication administration', 'nurse'),
  ('skill', 'Medication administration', 'pharmacist'),
  ('skill', 'Medication administration', 'student'),
  ('skill', 'Medication dispensing', 'doctor'),
  ('skill', 'Medication dispensing', 'nurse'),
  ('skill', 'Medication dispensing', 'pharmacist'),
  ('skill', 'Medication dispensing', 'student'),
  ('skill', 'Mental health awareness education', 'allied_health'),
  ('skill', 'Mental health awareness education', 'doctor'),
  ('skill', 'Mental health awareness education', 'first_aider'),
  ('skill', 'Mental health awareness education', 'midwife'),
  ('skill', 'Mental health awareness education', 'nurse'),
  ('skill', 'Mental health awareness education', 'other'),
  ('skill', 'Mental health awareness education', 'pharmacist'),
  ('skill', 'Mental health awareness education', 'student'),
  ('skill', 'NHIS registration and renewal', 'allied_health'),
  ('skill', 'NHIS registration and renewal', 'doctor'),
  ('skill', 'NHIS registration and renewal', 'first_aider'),
  ('skill', 'NHIS registration and renewal', 'midwife'),
  ('skill', 'NHIS registration and renewal', 'nurse'),
  ('skill', 'NHIS registration and renewal', 'other'),
  ('skill', 'NHIS registration and renewal', 'pharmacist'),
  ('skill', 'NHIS registration and renewal', 'student'),
  ('skill', 'Nutrition counselling', 'allied_health'),
  ('skill', 'Nutrition counselling', 'doctor'),
  ('skill', 'Nutrition counselling', 'midwife'),
  ('skill', 'Nutrition counselling', 'nurse'),
  ('skill', 'Nutrition counselling', 'student'),
  ('skill', 'Oral health education', 'allied_health'),
  ('skill', 'Oral health education', 'doctor'),
  ('skill', 'Oral health education', 'first_aider'),
  ('skill', 'Oral health education', 'midwife'),
  ('skill', 'Oral health education', 'nurse'),
  ('skill', 'Oral health education', 'other'),
  ('skill', 'Oral health education', 'pharmacist'),
  ('skill', 'Oral health education', 'student'),
  ('skill', 'Patient counselling on medication', 'doctor'),
  ('skill', 'Patient counselling on medication', 'midwife'),
  ('skill', 'Patient counselling on medication', 'nurse'),
  ('skill', 'Patient counselling on medication', 'pharmacist'),
  ('skill', 'Patient counselling on medication', 'student'),
  ('skill', 'Patient history taking', 'allied_health'),
  ('skill', 'Patient history taking', 'doctor'),
  ('skill', 'Patient history taking', 'midwife'),
  ('skill', 'Patient history taking', 'nurse'),
  ('skill', 'Patient history taking', 'pharmacist'),
  ('skill', 'Patient history taking', 'student'),
  ('skill', 'Patient registration', 'allied_health'),
  ('skill', 'Patient registration', 'doctor'),
  ('skill', 'Patient registration', 'first_aider'),
  ('skill', 'Patient registration', 'midwife'),
  ('skill', 'Patient registration', 'nurse'),
  ('skill', 'Patient registration', 'other'),
  ('skill', 'Patient registration', 'pharmacist'),
  ('skill', 'Patient registration', 'student'),
  ('skill', 'Phlebotomy for donation', 'allied_health'),
  ('skill', 'Phlebotomy for donation', 'doctor'),
  ('skill', 'Phlebotomy for donation', 'midwife'),
  ('skill', 'Phlebotomy for donation', 'nurse'),
  ('skill', 'Phlebotomy for donation', 'student'),
  ('skill', 'Physical examination', 'doctor'),
  ('skill', 'Physical examination', 'midwife'),
  ('skill', 'Physical examination', 'nurse'),
  ('skill', 'Physical examination', 'student'),
  ('skill', 'Post-donation care', 'allied_health'),
  ('skill', 'Post-donation care', 'doctor'),
  ('skill', 'Post-donation care', 'first_aider'),
  ('skill', 'Post-donation care', 'midwife'),
  ('skill', 'Post-donation care', 'nurse'),
  ('skill', 'Post-donation care', 'pharmacist'),
  ('skill', 'Post-donation care', 'student'),
  ('skill', 'Post-operative eye care', 'doctor'),
  ('skill', 'Post-operative eye care', 'nurse'),
  ('skill', 'Postnatal care', 'doctor'),
  ('skill', 'Postnatal care', 'midwife'),
  ('skill', 'Postnatal care', 'nurse'),
  ('skill', 'Prescription review', 'doctor'),
  ('skill', 'Prescription review', 'pharmacist'),
  ('skill', 'Prostate specific antigen (PSA) testing', 'allied_health'),
  ('skill', 'Prostate specific antigen (PSA) testing', 'doctor'),
  ('skill', 'Prostate specific antigen (PSA) testing', 'midwife'),
  ('skill', 'Prostate specific antigen (PSA) testing', 'nurse'),
  ('skill', 'Prostate specific antigen (PSA) testing', 'pharmacist'),
  ('skill', 'Prostate specific antigen (PSA) testing', 'student'),
  ('skill', 'Psychological first aid', 'allied_health'),
  ('skill', 'Psychological first aid', 'doctor'),
  ('skill', 'Psychological first aid', 'first_aider'),
  ('skill', 'Psychological first aid', 'midwife'),
  ('skill', 'Psychological first aid', 'nurse'),
  ('skill', 'Psychological first aid', 'other'),
  ('skill', 'Psychological first aid', 'pharmacist'),
  ('skill', 'Psychological first aid', 'student'),
  ('skill', 'Pterygium screening', 'allied_health'),
  ('skill', 'Pterygium screening', 'doctor'),
  ('skill', 'Pterygium screening', 'nurse'),
  ('skill', 'Pterygium screening', 'student'),
  ('skill', 'Pulse oximetry', 'allied_health'),
  ('skill', 'Pulse oximetry', 'doctor'),
  ('skill', 'Pulse oximetry', 'first_aider'),
  ('skill', 'Pulse oximetry', 'midwife'),
  ('skill', 'Pulse oximetry', 'nurse'),
  ('skill', 'Pulse oximetry', 'pharmacist'),
  ('skill', 'Pulse oximetry', 'student'),
  ('skill', 'Record keeping', 'allied_health'),
  ('skill', 'Record keeping', 'doctor'),
  ('skill', 'Record keeping', 'first_aider'),
  ('skill', 'Record keeping', 'midwife'),
  ('skill', 'Record keeping', 'nurse'),
  ('skill', 'Record keeping', 'other'),
  ('skill', 'Record keeping', 'pharmacist'),
  ('skill', 'Record keeping', 'student'),
  ('skill', 'Referral and follow-up coordination', 'allied_health'),
  ('skill', 'Referral and follow-up coordination', 'doctor'),
  ('skill', 'Referral and follow-up coordination', 'first_aider'),
  ('skill', 'Referral and follow-up coordination', 'midwife'),
  ('skill', 'Referral and follow-up coordination', 'nurse'),
  ('skill', 'Referral and follow-up coordination', 'other'),
  ('skill', 'Referral and follow-up coordination', 'pharmacist'),
  ('skill', 'Referral and follow-up coordination', 'student'),
  ('skill', 'Referral to mental health services', 'allied_health'),
  ('skill', 'Referral to mental health services', 'doctor'),
  ('skill', 'Referral to mental health services', 'first_aider'),
  ('skill', 'Referral to mental health services', 'midwife'),
  ('skill', 'Referral to mental health services', 'nurse'),
  ('skill', 'Referral to mental health services', 'other'),
  ('skill', 'Referral to mental health services', 'pharmacist'),
  ('skill', 'Referral to mental health services', 'student'),
  ('skill', 'Refraction and lens prescribing', 'allied_health'),
  ('skill', 'Refraction and lens prescribing', 'doctor'),
  ('skill', 'Refraction and lens prescribing', 'nurse'),
  ('skill', 'Refraction and lens prescribing', 'student'),
  ('skill', 'Shock management', 'doctor'),
  ('skill', 'Shock management', 'first_aider'),
  ('skill', 'Shock management', 'midwife'),
  ('skill', 'Shock management', 'nurse'),
  ('skill', 'Shock management', 'student'),
  ('skill', 'Sickle cell screening', 'allied_health'),
  ('skill', 'Sickle cell screening', 'doctor'),
  ('skill', 'Sickle cell screening', 'midwife'),
  ('skill', 'Sickle cell screening', 'nurse'),
  ('skill', 'Sickle cell screening', 'pharmacist'),
  ('skill', 'Sickle cell screening', 'student'),
  ('skill', 'Skin condition screening', 'doctor'),
  ('skill', 'Skin condition screening', 'nurse'),
  ('skill', 'Skin condition screening', 'student'),
  ('skill', 'Splinting and immobilisation', 'allied_health'),
  ('skill', 'Splinting and immobilisation', 'doctor'),
  ('skill', 'Splinting and immobilisation', 'first_aider'),
  ('skill', 'Splinting and immobilisation', 'midwife'),
  ('skill', 'Splinting and immobilisation', 'nurse'),
  ('skill', 'Splinting and immobilisation', 'pharmacist'),
  ('skill', 'Splinting and immobilisation', 'student'),
  ('skill', 'Stress and coping education', 'allied_health'),
  ('skill', 'Stress and coping education', 'doctor'),
  ('skill', 'Stress and coping education', 'first_aider'),
  ('skill', 'Stress and coping education', 'midwife'),
  ('skill', 'Stress and coping education', 'nurse'),
  ('skill', 'Stress and coping education', 'other'),
  ('skill', 'Stress and coping education', 'pharmacist'),
  ('skill', 'Stress and coping education', 'student'),
  ('skill', 'Substance use awareness', 'allied_health'),
  ('skill', 'Substance use awareness', 'doctor'),
  ('skill', 'Substance use awareness', 'first_aider'),
  ('skill', 'Substance use awareness', 'midwife'),
  ('skill', 'Substance use awareness', 'nurse'),
  ('skill', 'Substance use awareness', 'other'),
  ('skill', 'Substance use awareness', 'pharmacist'),
  ('skill', 'Substance use awareness', 'student'),
  ('skill', 'Temperature measurement', 'allied_health'),
  ('skill', 'Temperature measurement', 'doctor'),
  ('skill', 'Temperature measurement', 'first_aider'),
  ('skill', 'Temperature measurement', 'midwife'),
  ('skill', 'Temperature measurement', 'nurse'),
  ('skill', 'Temperature measurement', 'pharmacist'),
  ('skill', 'Temperature measurement', 'student'),
  ('skill', 'Translation/interpretation', 'allied_health'),
  ('skill', 'Translation/interpretation', 'doctor'),
  ('skill', 'Translation/interpretation', 'first_aider'),
  ('skill', 'Translation/interpretation', 'midwife'),
  ('skill', 'Translation/interpretation', 'nurse'),
  ('skill', 'Translation/interpretation', 'other'),
  ('skill', 'Translation/interpretation', 'pharmacist'),
  ('skill', 'Translation/interpretation', 'student'),
  ('skill', 'Triage', 'doctor'),
  ('skill', 'Triage', 'first_aider'),
  ('skill', 'Triage', 'midwife'),
  ('skill', 'Triage', 'nurse'),
  ('skill', 'Triage', 'student'),
  ('skill', 'Typhoid testing', 'allied_health'),
  ('skill', 'Typhoid testing', 'doctor'),
  ('skill', 'Typhoid testing', 'midwife'),
  ('skill', 'Typhoid testing', 'nurse'),
  ('skill', 'Typhoid testing', 'pharmacist'),
  ('skill', 'Typhoid testing', 'student'),
  ('skill', 'Vaccination administration', 'doctor'),
  ('skill', 'Vaccination administration', 'midwife'),
  ('skill', 'Vaccination administration', 'nurse'),
  ('skill', 'Vaccination administration', 'pharmacist'),
  ('skill', 'Vaccination administration', 'student'),
  ('skill', 'Venipuncture', 'allied_health'),
  ('skill', 'Venipuncture', 'doctor'),
  ('skill', 'Venipuncture', 'midwife'),
  ('skill', 'Venipuncture', 'nurse'),
  ('skill', 'Venipuncture', 'student'),
  ('skill', 'Visual acuity screening', 'allied_health'),
  ('skill', 'Visual acuity screening', 'doctor'),
  ('skill', 'Visual acuity screening', 'first_aider'),
  ('skill', 'Visual acuity screening', 'midwife'),
  ('skill', 'Visual acuity screening', 'nurse'),
  ('skill', 'Visual acuity screening', 'pharmacist'),
  ('skill', 'Visual acuity screening', 'student'),
  ('skill', 'Vital signs monitoring', 'allied_health'),
  ('skill', 'Vital signs monitoring', 'doctor'),
  ('skill', 'Vital signs monitoring', 'first_aider'),
  ('skill', 'Vital signs monitoring', 'midwife'),
  ('skill', 'Vital signs monitoring', 'nurse'),
  ('skill', 'Vital signs monitoring', 'pharmacist'),
  ('skill', 'Vital signs monitoring', 'student'),
  ('skill', 'Vitamin A supplementation', 'doctor'),
  ('skill', 'Vitamin A supplementation', 'midwife'),
  ('skill', 'Vitamin A supplementation', 'nurse'),
  ('skill', 'Vitamin A supplementation', 'pharmacist'),
  ('skill', 'Vitamin A supplementation', 'student'),
  ('skill', 'Wound and bleeding control', 'allied_health'),
  ('skill', 'Wound and bleeding control', 'doctor'),
  ('skill', 'Wound and bleeding control', 'first_aider'),
  ('skill', 'Wound and bleeding control', 'midwife'),
  ('skill', 'Wound and bleeding control', 'nurse'),
  ('skill', 'Wound and bleeding control', 'other'),
  ('skill', 'Wound and bleeding control', 'pharmacist'),
  ('skill', 'Wound and bleeding control', 'student'),
  ('skill', 'Wound dressing', 'doctor'),
  ('skill', 'Wound dressing', 'first_aider'),
  ('skill', 'Wound dressing', 'midwife'),
  ('skill', 'Wound dressing', 'nurse'),
  ('skill', 'Wound dressing', 'student'),
  ('specialty', 'Anaesthesiology', 'doctor'),
  ('specialty', 'Anaesthesiology', 'nurse'),
  ('specialty', 'Cardiology', 'doctor'),
  ('specialty', 'Cardiology', 'nurse'),
  ('specialty', 'Dermatology', 'doctor'),
  ('specialty', 'Dermatology', 'nurse'),
  ('specialty', 'Ear, Nose & Throat (ENT)', 'doctor'),
  ('specialty', 'Ear, Nose & Throat (ENT)', 'nurse'),
  ('specialty', 'Emergency Medicine', 'doctor'),
  ('specialty', 'Emergency Medicine', 'nurse'),
  ('specialty', 'Endocrinology', 'doctor'),
  ('specialty', 'Endocrinology', 'nurse'),
  ('specialty', 'Family Medicine', 'doctor'),
  ('specialty', 'Family Medicine', 'midwife'),
  ('specialty', 'Family Medicine', 'nurse'),
  ('specialty', 'Gastroenterology', 'doctor'),
  ('specialty', 'Gastroenterology', 'nurse'),
  ('specialty', 'Internal Medicine', 'doctor'),
  ('specialty', 'Internal Medicine', 'nurse'),
  ('specialty', 'Neurology', 'doctor'),
  ('specialty', 'Neurology', 'nurse'),
  ('specialty', 'Obstetrics & Gynaecology', 'doctor'),
  ('specialty', 'Obstetrics & Gynaecology', 'midwife'),
  ('specialty', 'Obstetrics & Gynaecology', 'nurse'),
  ('specialty', 'Oncology', 'doctor'),
  ('specialty', 'Oncology', 'nurse'),
  ('specialty', 'Ophthalmology', 'allied_health'),
  ('specialty', 'Ophthalmology', 'doctor'),
  ('specialty', 'Ophthalmology', 'nurse'),
  ('specialty', 'Orthopaedics', 'allied_health'),
  ('specialty', 'Orthopaedics', 'doctor'),
  ('specialty', 'Orthopaedics', 'nurse'),
  ('specialty', 'Pediatrics', 'doctor'),
  ('specialty', 'Pediatrics', 'midwife'),
  ('specialty', 'Pediatrics', 'nurse'),
  ('specialty', 'Psychiatry', 'doctor'),
  ('specialty', 'Psychiatry', 'nurse'),
  ('specialty', 'Radiology', 'allied_health'),
  ('specialty', 'Radiology', 'doctor'),
  ('specialty', 'Radiology', 'nurse'),
  ('specialty', 'Surgery', 'doctor'),
  ('specialty', 'Surgery', 'nurse'),
  ('specialty', 'Urology', 'doctor'),
  ('specialty', 'Urology', 'nurse');
do $$ begin
  if (select count(*) from volunteer_claim_eligibility) <> 564 then
    raise exception 'volunteer_claim_eligibility should hold 564 rows';
  end if;
end $$;
-- END GENERATED: volunteer_claim_eligibility

create or replace function enforce_volunteer_claim_eligibility()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  added_skills text[];
  added_specialties text[];
  refused text;
begin
  added_skills := array(
    select unnest(coalesce(new.skill_tags, '{}'))
    except
    select unnest(case when tg_op = 'UPDATE' then coalesce(old.skill_tags, '{}') else '{}' end)
  );
  added_specialties := array(
    select unnest(coalesce(new.specialties, '{}'))
    except
    select unnest(case when tg_op = 'UPDATE' then coalesce(old.specialties, '{}') else '{}' end)
  );

  select string_agg(s, ', ') into refused
  from unnest(added_skills) as s
  where not exists (
    select 1 from volunteer_claim_eligibility e
    where e.kind = 'skill' and e.item = s and e.category = new.category::text
  );
  if refused is not null then
    raise exception 'These skills are not open to your role: %', refused using errcode = 'check_violation';
  end if;

  select string_agg(s, ', ') into refused
  from unnest(added_specialties) as s
  where not exists (
    select 1 from volunteer_claim_eligibility e
    where e.kind = 'specialty' and e.item = s and e.category = new.category::text
  );
  if refused is not null then
    raise exception 'These specialties are not open to your role: %', refused using errcode = 'check_violation';
  end if;

  return new;
end;
$$;

revoke execute on function enforce_volunteer_claim_eligibility() from public, anon, authenticated;

drop trigger if exists trg_volunteer_profiles_claim_eligibility on volunteer_profiles;
create trigger trg_volunteer_profiles_claim_eligibility
  before insert or update of skill_tags, specialties on volunteer_profiles
  for each row execute function enforce_volunteer_claim_eligibility();

-- Self-checks ----------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_trigger where tgname = 'trg_volunteer_profiles_claim_eligibility'
                 and tgrelid = 'volunteer_profiles'::regclass) then
    raise exception 'trg_volunteer_profiles_claim_eligibility is missing';
  end if;
  if exists (select 1 from volunteer_claim_eligibility where kind = 'skill'
             and item = 'Physical examination' and category = 'first_aider') then
    raise exception 'a first aider must not be able to claim Physical examination';
  end if;
  if not exists (select 1 from volunteer_claim_eligibility where kind = 'specialty'
                 and item = 'Cardiology' and category = 'doctor') then
    raise exception 'a doctor must be able to claim Cardiology';
  end if;
end $$;
